# A simple action usage
name: Build Kernel
on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Android Kernel Build Action
      uses: dabao1955/kernel_build_action@v1.6.2
      with:
          kernel-url: https://github.com/rooteduniverse1003/TCL-A3-kernel-source-code
          kernel-dir: 
          kernel-branch: main
          config: bangkok_TF_debug_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          ksu: true
          ksu-version: v0.9.5
          android-version: 11
          aosp-clang-version: r383902
          python-27: true
          disable-lto: true
          anykernel3: true
          kvm: true
          nethunter: true
