name: Build lkm
on:
  workflow_dispatch:
  push:
    paths:
      - 'rekernel/**'
      - '.github/workflows/lkm.yml'

jobs:
  Build-lkm:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: build
        run: cd rekernel && make -j4 V=1

  Build-lkm-arm:
    strategy:
      fail-fast: false
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: build
        run: cd rekernel && make -j4 V=1
